name: Buf Push

on:
  push:
    branches:
      - master
    tags: ['v*.*.*']

jobs:
  buf:      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          # The token paramater is required to authenticate with the Buf Schema Registry.
          token: ${{ secrets.BUF_TOKEN }}
          # lint: ${{ github.event_name == 'push' }}
          format: ${{ github.event_name == 'push' }}
          # breaking: ${{ github.event_name == 'push' }}
          # breaking_against: ${{ github.event.repository.clone_url }}#format=git,commit=${{ github.event.pull_request.base.sha }}
