name: Buf Push

on:
  push:
    branches:
      - master
  create:
    tags:
      - v* # Trigger on tags starting with 'v', adjust if your tags differ

jobs:
  buf:      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          # The token paramater is required to authenticate with the Buf Schema Registry.
          token: ${{ secrets.BUF_TOKEN }}
          lint: ${{ github.event_name == 'push' }}
          format: ${{ github.event_name == 'push' }}
          breaking: ${{ github.event_name == 'push' }}